apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forward-auth
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: traunseenet
  source:
    path: forward-auth/app/
    repoURL: https://github.com/EislM0203/argocd
    targetRevision: HEAD
    kustomize: {}
  syncPolicy:
    automated:
      selfHeal: true