apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  destination:
    namespace: renovate
    server: https://kubernetes.default.svc
  project: traunseenet
  source:
    path: renovate/app/
    repoURL: https://github.com/EislM0203/argocd
    targetRevision: HEAD
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true