---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCzpTX4zw9fNc0gCFVoUxPDLdt0MFTzrjwY1Xzd8A8P5Kb40iXcpI22TEqkfGGe0uFUgpCDF9pp8BtdOPLFv7heRJZaoZv6mkcTgIKJ0qRh1QfnOWdvv+MyZIZDBzLwKMvYDzQd6c/9NrA+jWqBL74giR9k6kFtz1DFoG9H6BIxVI2/iwCaJbiA4j8kT/bDyf75e+GVpju7Kez6syPskkvet5o/jgOMZj/alN2XBliaYByM6tyB889H9gcIG4CAmJMaW7AtS2JmMVcTNVMvK5tAjGFnRy3f5D9xyHpZ/xVV2pX7PfhlgJ8YVrWad+nfeyap5n6jrX1MH/QtHuTCINiqWXRFViFSyip8Mc1zLzFFTSz5XYIIzvW/h/EiiZICv6Xq7rfU/hXC9yvSmZrIeB8O6x0JfFcu96hd2SVI/+8/tsF7sBvlqYlj7JIyghi5dorRo1MG9693tatnm4iKOr3vMaPRh7bErjSMb9r5zVCOvwxBeuSc1JIbdJ8muNATi3nHG4Dz7TqxH34ewhJyU1Y4HpDSP9AlA8ErbO/W4wWXgI9GO5SQe8oKyM6QW94qT6zal6JDinQCADGQ2ub2posb4qvSsOTBqOZtRI4QXSEmLid1/qZaKB6cPAbeAX78I/VZmYEDb+rNoX0DpnDubbNGqok6WnC5EWuZrUEPVZt16ZDaMbsJEgFB4OisxDyP6xNSzqO5rrUcFNTRN5SnZBXhwB6A2ShbKfKTApqZ9Kc+y9INN1sFw9V5
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
