apiVersion: v1
kind: ServiceAccount
metadata:
  name: homelab-secrets
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cloudflare-api-token
spec:
  method: kubernetes
  mount: homelab
  kubernetes:
    role: homelab-secrets
    serviceAccount: homelab-secrets
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app
spec:
  type: kv-v2

  # mount path
  mount: homelab-secrets

  # path of the secret
  path: cloudflare-api-token

  # dest k8s secret
  destination:
    name: cloudflare-api-token-secret
    create: true
    overwrite: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: cloudflare-api-token