apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ip-allowlist-middleware.yaml
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
    version: 36.3.0
    includeCRDs: true