apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ai-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 10Gi