---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portainer-longhorn
  annotations:
    numberOfReplicas: '2'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: longhorn-storage
status: {}