ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations: 
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    argocd.argoproj.io/ignore-healthcheck: "true"
    traefik.ingress.kubernetes.io/router.middlewares: traefik-ip-whitelist@kubernetescrd
  hosts:
    - host: portainer.local.traunseenet.com
      paths:
        - path: "/"
  tls:
    - hosts:
        - portainer.local.traunseenet.com
      secretName: letsencrypt-prod-local

service:
  type: ClusterIP

persistence:
  enabled: true
  existingClaim: portainer-longhorn
