apiVersion: v1
kind: ConfigMap
metadata:
  name: beyla-config
data:
  beyla-config.yml: |
    log_level: INFO
    routes:
      unmatched: heuristic
    discovery:
      services:
        - k8s_namespace: homepage
        - k8s_namespace: dashboard
    trace_printer: text
    otel_traces_export:
      endpoint: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/traces
    otel_metrics_export:
      endpoint: http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/metrics
    attributes:
      kubernetes:
        enable: true