values:
  serviceMonitor:
    enabled: true
  config:
    create: false
    ## -- Provide the name of the external configmap containing the beyla configuration.
    ## To create configmap from configuration file, user can use the below command. Note: The name 'beyla-config.yaml' is important.
    ## `kubectl create cm --from-file=beyla-config.yaml=<name-of-config-file> -n <namespace>`
    ## If empty, default configuration below is used.
    name: "beyla-config"