apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
helmCharts:
  - name: jaeger
    repo: https://jaegertracing.github.io/helm-charts
    releaseName: jaegertracing
    namespace: observability
    valuesFile: values.yaml
    version: 3.3.1
    includeCRDs: true