apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - sealedsecret.yaml
helmCharts:
  - name: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: keycloak
    namespace: keycloak
    valuesFile: values.yaml
    includeCRDs: true
    version: 24.3.1