production: true
replicaCount: 1
proxy: edge
global:
  defaultStorageClass: manual
auth:
  createAdminUser: true
  adminUser: markuseisl
  existingSecret: keycloak-auth
  passwordSecretKey: KEYCLOAK_ADMIN_PASSWORD
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    argocd.argoproj.io/ignore-healthcheck: "true"
  ingressClassName: traefik
  hostname: keycloak.cloud.traunseenet.com
  tls: true
  extraTls:
  - hosts:
    - keycloak.cloud.traunseenet.com
    secretName: letsencrypt-prod
postgresql:
  enabled: true
  primary:
    resources:
      requests:
        cpu: 1m
        memory: 1M
  image:
    tag: 16.4.0-debian-12-r9
  auth:
    existingSecret: keycloak-auth