---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      imagePullSecrets:
        - name: homepage-pull-secret
      containers:
        - name: homepage
          image: harbor-prod.traunseenet.com/traunseenet/portfolio:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: next
              containerPort: 3000
          resources:
            requests:
              memory: '1Mi'
              cpu: '1m'
            limits:
              memory: '1Gi'
              cpu: '3000m'
