---
apiVersion: v1
kind: Service
metadata:
  name: homepage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: homepage
  ports:
    - port: 8081
      name: homepage
      targetPort: 3000
      protocol: TCP