apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hoarder
  namespace: argocd
spec:
  destination:
    namespace: utility
    server: https://kubernetes.default.svc
  project: traunseenet
  source:
    path: utility/hoarder/app/
    repoURL: https://github.com/EislM0203/argocd
    targetRevision: HEAD
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true