apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate
resources:
  - secret.yaml
helmCharts:
  - name: renovate
    repo: https://docs.renovatebot.com/helm-charts
    releaseName: renovate
    namespace: renovate
    valuesFile: values.yaml
    version: 39.264.0
    includeCRDs: true