cronjob:
  # -- Schedules the job to run using cron notation
  schedule: '0 1 * * *'  # At 01:00 every day
  timeZone: 'Europe/Vienna'
renovate:
  config: |
     {
       "platform": "github",
       "endpoint": "https://api.github.com",
       "autodiscover": "false",
       "dryRun": null,
       "printConfig": true,
       "dependencyDashboard": true,
       "repositories": ["EislM0203/argocd", "EislM0203/go-projects"]
       "regexManagers": [
         {
           "fileMatch": ["\\.yaml$"],
           "matchStrings": ["image: (?<depName>.*?):(?<currentValue>\\S+)"],
           "depNameTemplate": "{{depName}}",
           "versioning": "docker"
         }
       ]
     }
envFrom:
  - secretRef:
      name: github-token-secret