apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argocd
spec:
  destination:
    namespace: navidrome
    server: https://kubernetes.default.svc
  project: traunseenet
  source:
    path: navidrome/app/
    repoURL: https://github.com/EislM0203/argocd
    targetRevision: HEAD
    kustomize: {}
  syncPolicy:
    automated:
      selfHeal: true