apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
- secret.yaml
#- pvc.yaml
helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    releaseName: harbor
    namespace: harbor
    valuesFile: values.yaml
    version: 1.17.0