---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgB6TEPbflIDLHek2FRLefJjs4KuGNnAQ1YD/TdsfvYe7b4cxzRidb8/lZW+WiWHx3DRdLLxuvCqmq6ONC4oCsqlftJDSWSM8u3nN57sudAlTnUMjUTwWefJpOOt8Cz16coY4FztIHGRAjNUnX5P+IDYJWC+j7r0yNE8vdt0FDkMfthq8Qhqr+yPUBIRuzly3Mgkcmqnv+8UO+H7iJZreDjx9zl5iDallaZ9wu1AL/mLhMmm6AjzrAMOzry3mPZl96wMQy6t0Ewz0ObrAOeU+aZ+bPFpOCv8GeTHCy7TR2g1+YyuLXiDC/xCMrvDvE8RR2MbTZTcFFss7v+1Q/WDjlmTVNY8quUhzUDdP1XxEUnJ+HF+SxEVdKfoN0huJNAiZiKZProPmVd1zHi9g16fpT42+kgC7RudjA6CgV3PO+zzPc5cXjtOOHDifR1KgdJrhbzIaMvRskl9MKqsE8fJUy9kLwioPbAq0l00XYKVy0/YVDhHqgrNbkwvW4o2IYL64BBLlk99HqQEw53HZD8IQ6/HZq4eVJ0NYb4OkWI7CJvBs9nZhPhUbzkWIY+tJkmTEyBUKRDC3hx+TRcdZxj3QUWeX+KoIb90eZSaksFO68Q3MvbR7sUgWpyJwo+oSJW7XByVjznFrkV/A2vqvOa1aGC++xv/asFWJbf+ocnYSsLAUTOFzKzGw3qFP69kjZRkblZBONsM5gDoXEKjaJO93bA2mZZWSbyiXoCcW6CJaVjQW5Y=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-secret
      namespace: harbor
    type: Opaque
