---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-storage