apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
- ingress-local.yaml
- secret.yaml
helmCharts:
  - name: paperless-ngx
    repo: https://charts.gabe565.com/
    releaseName: paperless-ngx
    namespace: paperless
    valuesFile: values.yaml
    includeCRDs: true
    version: 0.24.1