---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-server-secret
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_SECRET_KEY: AgDRE/TyN6rqqXyRGaVDXQTB3DrfxIS4wFsBQQojJY2mZJObJgPMelcCtOrg/Vdnhy7H34LaKT7xGjEhwC+RHkAPNBLfponH8mf/bGcrnhCmADcbyLeziOl8VXglM+tIeCkpkuR00dliwuWDdTQfty/0dEoH5q/vNlfrs+GCdyecI/yc/f2fuyfjPBr2/ZFucHueJj6FsCxLIhJ2TeUtbkyD9eyFomCJpGgYCXFrJasNKu2N2P9BJ93yGIcqMKJ0Wc/9dVJi1/14vAM36VpHEDWqhXzIpmjJBd7yvh5sCtokevUyGbMpjj8oO5ySAn6iw55GNQ6uiRxdzo94tdybkiX/zg3d+K6zd7rCjrEtrkaPfGfJfcoeRGDbd51/gtHK+UqBFaYXlDeyu+3o7UxjQ0pAz3ud3OWAXrZPcIyRAzvL5mpO+O+LXpPJXdzaQtOm7RRzGXzPOgqlYFFyrYZ3GoyNx3W1BzyN+N4vaZyF6rXHxrpCR7CT4iIu5A+7gcUtlqZLvkTfoJBvaG2z8sFKdhNQoom+lDOLYKzeKjJuTSGKUL9rRQJYpnPmfn51FIiQkCh6OFcY657c6CESB5xoJWpi5CELTymRS0TsHtPkMJfQEYoDs1mo9grYvzrGp2Gv6Wr3QvaIFO/Qz+53XqGIeE3lYdHov3+EJ5UHtPTGEesrXWZ9Qj3BdPyVhKsRcPhBw8+H7txKFVdkk9tE6ORK8Ri5D7Q=
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: AgCaGGdZxuX5nZ7hiaNOWs3J4V+olJm3uj83QqAiBbD7mryivpfoNj7OZbyyJKP+TRZj/ods5MRL6gAHoIdhhQeC5eT2/wXCwHD41lBT6nxp5D/zK7/oLiIzf1kCY4MvIisX/Ly+gEuGqtCJMVhn1lJFkDOwAkEsJwD3fA3eKpZQfn4Yc1nHmKfC8Ie86sY769VHr74tJsQ8AhNXVJHO9OpgmFKisiOvk03Le1QT4m/KG9QwUQsyjg337t/xcex9sSrPWkgeZqn+vCXwCnqjjeB37m7wKgLQtCf9kfjycTOcKGCpzJJcvtum3+NUSCa8ZD4kjlLY3hzY4jCNCrMunPGk2XqilYT5quNyIvaaUPcCtiX3V1E4oSoFP9g6lAOsS8vILj1G1rfBxG1b87yPOW0QISFT7muVJpKarYh8gdHqrSTfjFBnhmi5XosrxOdXmPOvFF8UR/WeogXfvjutFNWBbpgFJi40enu7Z5Krdv0zgs+jDA9SmkrlXJsmuAbMG+VYb9gZ8pvbl4QGCToDXVrHmfk5SnjuvpsxU1IXzWTrCbcntFBY39cAZfHTRe8RYCF4epEvYVF7J3zYZIRneVsZzP9Rh+5nd9zYeqq2cufjiscfw8OQK55fKUU11UIqNNg0FL8JAt82zwpLfrTJYmGVXv4A8fSXtl45h1Ns/Y2g46hcePVdx8knKqJsMPn3kY91GFbF4yy2tpTzhLBGl/TJW8lk7iz9UNA/NNoSC/ceJhxYxIaLQYreuFrnceGoMucSE+skrfSQuJd4f2RMy0zljX8v4rVIF6OYPg05CqJUtXkVBD09p3UJqpb92nmFNB7TdV3qpTW4CG5O9KV8OzswYiXmfzYA4mDHlxigt2w4HGhinqvi2J6j548Rl01kXvkwj3sKnJprdavIP2d/9TNjS30Avi2weRr4LLE+uaXPb51AiFa3I4CsLEUJbmjfHZBJULFiIvDpA6qkg24pR42kI5mOiQ==
  template:
    metadata:
      creationTimestamp: null
      name: paperless-server-secret
      namespace: paperless
    type: Opaque
