apiVersion: v1
kind: ServiceAccount
metadata:
  name: homelab-secrets
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: paperless-ngx
spec:
  method: kubernetes
  mount: homelab
  kubernetes:
    role: homelab-secrets
    serviceAccount: homelab-secrets
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app-postgres
spec:
  type: kv-v2

  # mount path
  mount: homelab-secrets

  # path of the secret
  path: paperless/postgres-secret

  # dest k8s secret
  destination:
    name: paperless-ngx-postgresql
    create: true
    overwrite: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: paperless-ngx
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app-redis
spec:
  type: kv-v2

  # mount path
  mount: homelab-secrets

  # path of the secret
  path: paperless/redis-secret

  # dest k8s secret
  destination:
    name: paperless-ngx-redis
    create: true
    overwrite: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: paperless-ngx
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app-server
spec:
  type: kv-v2

  # mount path
  mount: homelab-secrets

  # path of the secret
  path: paperless/server-secret

  # dest k8s secret
  destination:
    name: paperless-server-secret
    create: true
    overwrite: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: paperless-ngx