apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
  annotations:
    numberOfReplicas: '2'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-storage