---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-longhorn
  annotations:
    numberOfReplicas: '2'
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 50Gi
status: {}