---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: minio
spec:
  encryptedData:
    password: AgCrPHlIa20kyE6QSiwmIpEdXrCGPineAUlo2haCzxu/bwqtcDVajEs/hrV2kkWPakahZ5fws5q1pNvxIgYs52e1sdyC1THB6sKHqNiBSx1aMoJp11ul1vW/VWKuTNrVr34oAgq64t2ANKIBkIM5bJNZDvPUcCYTO23BK+8GjryWoK6msr+JXU1nuqYuEjXNxMqqzzc8cdejV784cfiP5/buQnLeuADMkyPAjJNz4BummtVwQsahZofBUSljguvN3AWqQyBcg3rvZ25ll9veND1tNtSrUYSF4DB9/ZmHuIB8ameQOC20sahJhTz/fMEBx57qnHAwKMS7o5lHKoW4W2vaMqH4NiGyNsQ8NvVWZrcx9d5gD40dNGjlw9YKtjbmXBaChjONVYvnXxNkT1rIx7WDXP5EwqF9Dywgu26XO/TTIRkU7YTkINgGztMXUSh22G+9YAsKsSEC0lPegDPIt32hqMljyx2k+CZ/3QV+dwpfpgR+9wdV3p/RUXoHPwM8hI8j8rF7bJQKqR2gMjDM7OO7op9j0xExEhaHnkGhXompSF2QNx58cBY/2clW1HETJmb0TsMC4Cbgac3dkB6EpvAdC/6OWajaV1wHGKQPgPckmG5q7tgS58JGO44rlG/+cwSyzm9h/qkOhFGxTJakWV7br0JKbnnpiSxRXPEwlFB4zY4gcQSTvCGsNzF+5W99LETiRD0GUAvJdGphLi2lAZTfz7tVEtkV99+ltXo6X6IG2g==
    username: AgCuPJ9/ZwCxobrphgvdGuSes/xn7OchQSMPOU44PAWA2+cxEwQYxBC5nJ2mwVttKcMDYzvCklo9gyfQCsk0ECmufTCyPGwrqjvbzukoAgZW2MupK4zsL7gy04mJv0HpkaxOYUpTLzqmPVblCV3pKdNrcP51xy9Ccteg3bQOs5R3a1clMflt26k7w+oBhqhSkS7grPnxd2I0rbzej501q6KYQjLYONKYJFmckadQuj/n77moDMeaL3ljI5BBSL6fPxIMdXIdUYTt0DrFWRqGfjt3vyXZ6pdWV4D9EJnBC/E8BpBfpjk0cwm3mgX/WUx9+IRGXxAFunPHEHMtpNGH3YtKjgPKCXgV31qrhcAroVnP6VTGZ4NteJizgTu3fccjQzfNk4P2vaNTx+jGto1xKJzjqEztWmpUK9U+vNmCiy/UVEA0ecRP8q7JTv34ULd5Bz42nt4Xgynu21NCvQ7xGVSkhjj/69dftY5Mn8hAs4AqU6Un5s6mXxuFGspL8bCKtOhgkO7uslYHHs7fuggQ468PdIQLXiidVzT2EnxMPCx6mYQlejlzCZWH8c3PYuBJDBvYC0F/N5z/3aHPGpeiU46wOjEVzfmPYnFNgMfOIiXgnlHhD70rv7r7RSyDl6uYEr+7jPsMCsB3/vB08fjjQcL16N4r8wg3H8Ebk+t2pIXBV4wr/yx0JyZvJQSUvjnXD6JJT79Hr4RvdLDKUYdjQQB+
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: minio
    type: Opaque
