---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: minio
spec:
  encryptedData:
    password: AgC1VAyPPhmtK0Mzj3cZGaWGCNQMZx+orT85wEj4UPF7k63YZNtEYceXEny6TOZ1a30Evvgq88L1pZcUzwCduudEmsbGY20iLg0bKmDRAAW74vekENa7TEGdbmZMKyc6VHVhxUKCVhyeWMhWQFYl6ylLqpZ8ISyZKLHV6DmKzI8hNoNHy2ldQ5yyA8ZYnilrhavdtJ1uJksfrC0Zr4OsaRD/zHTk4YpeWktYPADisputPksgIe3YlS8xA7eUNKCl8N39JDIDdWd/iKocTpzRjo6woDz/980LVvOfjFMYCdaSws5G/6okFFn3mRId8ldKbwmMvDhVZKa4qc1bTNv6zgdXPhbdewPdsdFYx/cpGjO9Aj93J1TQQkcmqjpMsTqVbvMgTv80+cHORoWoBIqFrPVBbYtHSFcRotnFqsgFdkO4S7c8jv1nyKJY4BVSS/yqgXVRcc+o+0ioaGFyZMZKzgM7eQNQHT6gHAhVLRQmagNoa/4ejPTGHgT+7YDN3H38jkBW8s/+W+KNgt7gp6BZgN93qlqls9whg+12og/XM5lXT+dnUkOOb+ICkBHAfU2q6FdxfcQ7r2vAB6b3oodoNV4jRH54qGzhmCugNZzfDJyKJnCK/Lmr007EAk2Jk6j3ps9+gD2NlljDAovtYtNOM6yl03pNwotqBrRNUNYLN2YR3hB1rhZJcN5YPlwJurfZv7v5cDJr1pjCrhoe/7lbsNH75WZVo32Ong==
    username: AgC1dguNz93vZIKoDwzOMXRuCGzfsPPiHJLVLksV7VUaAJPTQz3eL8mDld9aGn2/mmRCaQKpxXNGPrUPw+58WUbdXqMf6K93SktIbOXxoMVuRcHXxFhA8oHFqCne+aS7tTi9/ANbxSoAgs8n9YPdOEFyvCkEhXjzlkSGzMuRQo0OaYNjvwYGzpnqO9Ox4Aj45Y24slzP/feh86cJAKyeYqnYsELAmaQEA0N7vAzx0B8eK7ZAwQ8G51w/uEEvWBypvPRi7GS35h7X28hW8o1MIuT10FdRSPh5MW3Ujp61sI4lK/CcxNjeDPYiEomGF34o9nFp4KxC2EZg/f+YAUIPXCNzJWqUW4kgfdfhCWR5xChxxCYb1L5cpQ7+hrjZ1N0vya0c+2UNv4WFsCrVZ494D8pKHd3m/mf42jR/0Xyc3fzeZ7c+jkBN8agkiZpmWZkOR3uMAHC/MoZ6NUaKkOOvMGjBeKG0g+zQjP2EGbJWsuLU4T9xttJxb+2J96Kwhazic3JxIPjIg3esNaHr52dK9OCe+DljgLIaRx96Y2L0tLkM4D3bzQuawNLZbYEX+HK/7DWz9JVan632lnLU/sZ3m1Tt3T7YoAeh2eeJ9cz9T/OM8bHaNBtwwvmRGfr6O3w9eDIs1Hhm9XH9rIRnYCjkU/KwNmDWrzv/ADouAIMulyZCIhdSjs1ixPd/G1oAL9RB6i7XlaQ3HTfPsdL+
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: minio
    type: Opaque
