---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secrets
  namespace: minio
spec:
  encryptedData:
    password: AgAtq/Im57KOxpl3yhr68UVRGjOfFE1Rz2KrqhhVa7d2o3Hql0DPz6e85AEXPUgm/T5AdQ8tbEmvotcXrjegjH7V94imATzyBqtwy/YZAJDEKgIR4tJC6i6n1H8jbAwO2FiWL+DLmWjWdrfkJCgc/nHkV/wXgMHeQUrWWB8iEcxI82LKB3EPn0W488Fxs5h333f/lCVpmbdvk9uHkJfr5Vs55LVgt3pxKVu24eq21YPobMeQE9oxRO8eef4lLtvkjLhVvgthyJRR8M0XUaSbw9JSFduJAp6UIzGtMQakjZ0n5U7mom3fwoce8nzoG4/pJ4/HuE8N6uOrQ6fBWpdjEo2t6XlFkMTtQJchmfaUdsmwzvKrxWaTAJqzg6w8CEvMsklfsJD58VNR3eEKe6wvYsWuj7G2dCntWS2Zjq46Yg3gGy8RjIe7RVZWOB6soVDzqFMVWG+h1xYz+DfyQCv8vloEuwNPKyY3DAUwweA1EkVq8dLw8bfmhk8sXCug2mlAWSN1e11JdQpDNsFHORc0Srl+5SlGx2W2hh2ZfKL7Y7kPkmAVvR2hCznRkl80I5swXoe+2d7EP4adyRR0coiaVyrNo37vtSW0EAH9UWuQMF+bsFSx5J2N36kpeOUdWpHdnG4ar8i/XhswAWMHUv4XUWGi/vfubuTkU0v/F8V6GcQnYM6ogldA0KlCsAyKml3RFlHJpPn0imCXoWQDv4SoBNMbJ2pQITE2kA==
    username: AgCLjIbs7ROyvgnKZ11GLVeufFcq6rEUTLkeAd+SATtMAN2mwvhYqfeAX86pkn3mr/NsqaDjHl32N0lOwxYHdKRlo+t51nnACEE4jI6OR2vr/xnmtELXwC7S1Cz7CiE/dO9WHBTF18XwIPYPvxtX4ZvsslorpMtZHCl54QX0S9POsABuEnfnDRYqFTXWDRGz5R0na3n9quDlfos5ceadGahSY5FaywMXIpfRbJkxGy1qIQhdPt8oRLQhRVYVys20hzXmxUQIT34svFtg+MPlEjp9HTr1CFsgh8M5E/AxHerYgfE+nbUUCQsZXd79disNvaL9IPxiWzzq/LEVDG0qZtI1KSjtDQzdA+xLmVy5icSuKcMSxLUlvv6gToCWwgadxi60HpdBhjHkQLXTkf4RHtlpRXKD4eKYBghtVRr3FpnVl2VtqGrutJb0IfmNSHYsxGutHdj+OEKg7+y67QySSo10x7Z6Oc4J6SvsJi6cLt9BMxYnlrqWFJRzI6YPNgHm92AdH8VLJ8/8NxlgN+K4EOmp5I2M/ZIdvl3fZTomzz3gfuCnOlNxQQ/LaIXqNp6RxQYsKySWgolN48NbBC+EvhH3SC6g2nvCWgrs+lffa78If6KDIk2PTLjNkQxGaK6FIWdN4B2Bf/MKtdaP0dAcGPGgi1caHHKomUrcZU8tAafZJ4yPa3n2/epYg8nfPjLiUkrzBnJvQfOH4Q1Q
  template:
    metadata:
      creationTimestamp: null
      name: minio-secrets
      namespace: minio
    type: Opaque
