apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  kustomize.buildOptions: --enable-helm
  accounts.admin: login, apiKey
  resource.customizations.health.ingress.networking.k8s.io: |
    health.lua: |
      hs = {}
      hs.status = "Healthy"
      hs.message = "Custom health check: ingress marked as healthy"
      return hs
