apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: traunseenet
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Traunseenet
  sourceRepos:
    - '*'  # Allow all repositories
  destinations:
    - namespace: '*'  # Allow all namespaces
      server: '*'  # Allow all clusters
  clusterResourceWhitelist:
    - group: '*'  # Allow all API groups
      kind: '*'  # Allow all resource kinds