apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: traunseenet
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Traunseenet
  sourceRepos:
  - '*'
  destinations:
  - namespace: dashboard
    server: https://kubernetes.default.svc
  - namespace: homepage
    server: https://kubernetes.default.svc
  - namespace: open-webui
    server: https://kubernetes.default.svc
  - namespace: sealed-secrets
    server: https://kubernetes.default.svc
  - namespace: traefik
    server: https://kubernetes.default.svc
  - namespace: keycloak
    server: https://kubernetes.default.svc
  - namespace: longhorn
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: v1
    kind: ServiceAccount
  - group: ""
    kind: Namespace
  - group: networking.k8s.io
    kind: IngressClass
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition