apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: traunseenet
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Traunseenet
  sourceRepos:
  - '*'
  destinations:
  - namespace: dashboard
    server: https://kubernetes.default.svc
  - namespace: homepage
    server: https://kubernetes.default.svc
  - namespace: open-webui
    server: https://kubernetes.default.svc
  - namespace: sealed-secrets
    server: https://kubernetes.default.svc
  - namespace: traefik
    server: https://kubernetes.default.svc
  - namespace: keycloak
    server: https://kubernetes.default.svc
  - namespace: longhorn
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  - namespace: headscale
    server: https://kubernetes.default.svc
  - namespace: navidrome
    server: https://kubernetes.default.svc
  - namespace: utility
    server: https://kubernetes.default.svc
  - namespace: immich
    server: https://kubernetes.default.svc
  - namespace: observability
    server: https://kubernetes.default.svc
  - namespace: portainer
    server: https://kubernetes.default.svc
  - namespace: seafile
    server: https://kubernetes.default.svc
  - namespace: jellyfin
    server: https://kubernetes.default.svc
  - namespace: minio
    server: https://kubernetes.default.svc
  - namespace: renovate
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: rbac.authorization.k8s.io
    kind: Role  
  - group: v1
    kind: ServiceAccount
  - group: ""
    kind: Namespace
  - group: networking.k8s.io
    kind: IngressClass
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: scheduling.k8s.io
    kind: PriorityClass
  - group: storage.k8s.io
    kind: StorageClass
  - group: cert-manager.io
    kind: ClusterIssuer
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
  - group: ""
    kind: PersistentVolume
  - group: monitoring.coreos.com
    kind: PrometheusRule
  - group: monitoring.coreos.com
    kind: Prometheus
  - group: monitoring.coreos.com
    kind: Alertmanager
  - group: monitoring.coreos.com
    kind: AlertmanagerConfig
  - group: monitoring.coreos.com
    kind: ThanosRuler
  - group: monitoring.coreos.com
    kind: ScrapeConfig
  - group: monitoring.coreos.com
    kind: PrometheusAgent
  - group: batch
    kind: CronJob
  