apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: note-mark-pvc
  namespace: utility
  annotations:
    numberOfReplicas: '2'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-storage