apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-system
resources:
  - barman-cloud-plugin.yaml
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.io/charts
    releaseName: cloudnative-pg
    namespace: cnpg-system
    valuesFile: values.yaml
    version: 0.25.0