apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  annotations:
    numberOfReplicas: '2'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 5Gi