---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hoarder
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  tls:
    - hosts:
        - hoarder.cloud.traunseenet.com
      secretName: letsencrypt-prod-hoarder
  rules:
    - host: hoarder.cloud.traunseenet.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
