apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: utility
resources:
- web-deployment.yaml
- web-service.yaml
- chrome-deployment.yaml
- chrome-service.yaml
- meilisearch-deployment.yaml
- meilisearch-service.yaml
- meilisearch-pvc.yaml
- data-pvc.yaml
- sealedsecret.yaml
- ingress.yaml