apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.6
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: HOARDER_VERSION
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: HOARDER_VERSION
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: NEXTAUTH_SECRET
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: MEILI_MASTER_KEY
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: NEXTAUTH_URL
            - name: NEXT_PUBLIC_SECRET
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: NEXT_PUBLIC_SECRET
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: meilisearch-pvc