apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-pvc
  annotations:
    numberOfReplicas: '2'
spec:
  storageClassName: longhorn-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi