apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoarder-web
  template:
    metadata:
      labels:
        app: hoarder-web
    spec:
      containers:
        - name: web
          image: ghcr.io/hoarder-app/hoarder:0.18.0
          ports:
            - containerPort: 3000
          env:
            - name: MEILI_ADDR
              value: http://meilisearch:7700
            - name: BROWSER_WEB_URL
              value: http://chrome:9222
            - name: DATA_DIR
              value: /data
            - name: HOARDER_VERSION
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: HOARDER_VERSION
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: NEXTAUTH_SECRET
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: MEILI_MASTER_KEY
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: NEXTAUTH_URL
            - name: NEXT_PUBLIC_SECRET
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: NEXT_PUBLIC_SECRET
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
