apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoarder-web
  template:
    metadata:
      labels:
        app: hoarder-web
    spec:
      containers:
        - name: web
          image: ghcr.io/hoarder-app/hoarder:0.22.0
          ports:
            - containerPort: 3000
          env:
            - name: CRAWLER_VIDEO_DOWNLOAD
              value: "true"
            - name: OLLAMA_KEEP_ALIVE
              value: "1m"
            - name: INFERENCE_JOB_TIMEOUT_SEC
              value: "600"
            - name: CRAWLER_FULL_PAGE_ARCHIVE
              value: "true"
            - name: DISABLE_PASSWORD_AUTH
              value: "true"
            - name: DISABLE_SIGNUPS
              value: "true"
            - name: OAUTH_WELLKNOWN_URL
              value: https://keycloak.cloud.traunseenet.com/realms/master/.well-known/openid-configuration
            - name: OAUTH_CLIENT_ID
              value: hoarder
            - name: OAUTH_SCOPE
              value: "openid profile email"
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: OAUTH_CLIENT_SECRET
            - name: OAUTH_PROVIDER_NAME
              value: Keycloak
            - name: OLLAMA_BASE_URL
              value: http://10.0.0.141:11434
            - name: INFERENCE_TEXT_MODEL
              value: command-r7b:7b-12-2024-q4_K_M
            - name: INFERENCE_IMAGE_MODEL
              value: moondream:1.8b-v2-q8_0 
            - name: MEILI_ADDR
              value: http://meilisearch:7700
            - name: BROWSER_WEB_URL
              value: http://chrome:9222
            - name: DATA_DIR
              value: /data
            - name: HOARDER_VERSION
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: HOARDER_VERSION
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: NEXTAUTH_SECRET
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: MEILI_MASTER_KEY
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: NEXTAUTH_URL
            - name: NEXT_PUBLIC_SECRET
              valueFrom:
                secretKeyRef:
                  name: hoarder-secret
                  key: NEXT_PUBLIC_SECRET
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
