---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-storage
  annotations:
    numberOfReplicas: '3'
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 10Gi