apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - secret.yaml
  - sa.yaml
  - ingress.yaml
  # - pvc.yaml
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    releaseName: vault
    namespace: vault
    valuesFile: vault-values.yaml
    version: 0.30.0
    includeCRDs: true
  - name: vault-secrets-operator
    repo: https://helm.releases.hashicorp.com
    releaseName: vault-secrets-operator
    namespace: vault
    valuesFile: vault-operator-values.yaml
    version: 0.9.1
    includeCRDs: true
