---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hashicorp-vault-data
  annotations:
    numberOfReplicas: '3'
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 4Gi
status: {}