apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-immich-2 # Needs to be set to "db-immich-3" if you need to restore the backup. Otherwise you risk loosing the data
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0
  instances: 1
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  storage:
    storageClass: longhorn-storage
    size: 20Gi
  managed:
    roles:
      - name: immich
        superuser: true
        login: true
  # Used for first deployment. Never reuse it, it WILL wipe the data
  # bootstrap:
  #   initdb:
  #     database: immich
  #     owner: immich
  #     secret:
  #       name: immich-postgres-user
  #     postInitSQL:
  #       - CREATE EXTENSION IF NOT EXISTS "vectors";
  #       - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
  #       - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
  bootstrap:
    recovery:
      source: source
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: immich-store
  externalClusters:
  - name: source
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        # Recovery Object Store (pull, read-only)
        barmanObjectName: immich-store
        serverName: db-immich # TODO needs to be set to "db-immich-2" if you need to restore the backup
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: immich-store
spec:
  configuration:
    destinationPath: s3://cnpg-backup/immich-backup
    endpointURL: http://minio-service.minio.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: immich-postgres-user
        key: MINIO_ACCESS_KEY
      secretAccessKey:
        name: immich-postgres-user
        key: MINIO_SECRET_KEY
    wal:
      compression: gzip
---
# Single Backup
# apiVersion: postgresql.cnpg.io/v1
# kind: Backup
# metadata:
#   name: immich-backup
# spec:
#   cluster:
#     name: db-immich
#   method: plugin
#   pluginConfiguration:
#     name: barman-cloud.cloudnative-pg.io
# ---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-backup-scheduled
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: db-immich-2 # Needs to be set to "db-immich-3" if you need to restore the backup. Otherwise you back up the wrong cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
