---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc-ml-longhorn
  annotations:
    numberOfReplicas: '3'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-storage
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc-server-longhorn
  annotations:
    numberOfReplicas: '3'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn-storage
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-immich-redis-master-0
  annotations:
    numberOfReplicas: '3'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-storage
status: {}
