## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
## Refer there for more detail about the supported values
env:
  DB_HOSTNAME: db-immich-2-rw
  DB_PORT: 5432
  DB_DATABASE_NAME: immich
  DB_USERNAME:
    valueFrom:
      secretKeyRef:
        name: immich-postgres-user
        key: username
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-postgres-user
        key: password
  
  LOG_LEVEL: info
  TZ: Europe/Vienna
# These entries are shared between all the Immich components
image:
  tag: v1.134.0
immich:
  metrics:
    # Enabling this will create the service monitors needed to monitor immich with the prometheus operator
    enabled: true
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim: immich-pvc-server-longhorn
  # configuration is immich-config.json converted to yaml
  # ref: https://immich.app/docs/install/config-file/
  #
  configuration: {}
    # trash:
    #   enabled: false
    #   days: 30
    # storageTemplate:
    #   enabled: true
    #   template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"

# Dependencies
postgres:
  enabled: false
redis:
  volumePermissions:
    enabled: true
  master:
    nodeSelector:
      kubernetes.io/arch: arm64
    resources:
      requests:
        cpu: 1m
        memory: 1M
    persistance:
      enabled: true
      existingClaim: redis-data-immich-redis-master-0
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  image:
    repository: bitnami/redis
    tag: 7.2.4-debian-12-r12
    pullPolicy: IfNotPresent

# Immich components

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false
      annotations:
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.local
          paths:
            - path: "/"
      tls: []

machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      # Optional: Set this to pvc to avoid downloading the ML models every start.
      type: pvc
      accessMode: ReadWriteMany
      existingClaim: immich-pvc-ml-longhorn
      # storageClass: your-class