---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-gpt-prompts-pvc
  annotations:
    numberOfReplicas: '3'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 1Gi