---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: obsidian-remote-pull-secret
  namespace: syncthing
spec:
  encryptedData:
    .dockerconfigjson: AgBu12v5ZHzkL0NaYcaKIEwb242BgX+71aFXlsDgThEbG5Yl6c7FNserD6xgjGJeI3SzBeso0/qK0Wlt73iz5oz/ggKR8XnNpdkB1eeROsnTZl34DNtcGphU83mbTxymwG04Z8fIEaeIcM1ep7XMCefX0GQCaeOmKSC1Rogw0+ofBFdHLa5QQZ2RXE4kSIxdaaR3Els8I3UBw0hnlZsFGu6DiORE8nFFEJxmUVrzXmPqsLzTYOr+AbOm0wGgv7huVDY0HheIIAMPD5TT84x+RTHj0+fCKA2kSImoJIqW+5IhGI6+vYPiZpJJ/umqiMQRNVot/gOhZkRMEFDoUM1DCBuoW1fq5Wf30HvnMvS32twrXY0+GfYPnJDXe4C4cTc7Twv0Q+rga4syIM2y9F/DNN5ExOHdyspbB4eXFw7xM8YtRjpCQSsfjHcqQQye51i3NvS1PNEWQIJFCUgN4K/myh2fmcWkIWRcE9JVD3VPPgPFEpWulwanOB1GOglVAVSkRbNAD3ga7SG8UEBjTAKqw1CfMhYz5Yp99Mk0KigE+Pft+SctObG4OGTftDaog7o/nY1p0JrrOxT0IuQXe2LFYx1WK2rBeQI0AaQq+5csOZLGN7JfYcAdDdkBX9WWV7aA+gMqNTv3rQWuf9ESLx1qDqJQBUuCF1dHNXW5kY605+T5OYgv1weRZ6LIyc1n+E6ptmEPSsdN7Fkwvgx+k+cvcs3MyFhLj1INMdZZvcchA1OXoRIQoanQ9om3xiWr+UlgidFXh7wdgE09PMrq9lhfzc3qOYD8sI2A9zxPrKHMoHApfOkI30lTKI2zrxAJq8QEyR2ELWE3O+4NJn7Ic4M7uFwDRh4CADHyGS8+6j09yANQqvRui3w7+Ap55Zh5jhAhI3l6sSKmdrk80Z7Y7mjGsTSzToUNpAsFpYQ6DXo=
  template:
    metadata:
      creationTimestamp: null
      name: obsidian-remote-pull-secret
      namespace: syncthing
    type: kubernetes.io/dockerconfigjson
