apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - pvc.yaml
helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: observability
    valuesFile: values.yaml
    version: 8.5.8
    includeCRDs: true