---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAnHaJBS7ewS4cU/7wEv2fAWl1goyjO6zIoOJDtENOEcIdc+EgvVUSQs0wxbIK2Y1Tu98FYST15wvq34m3FlJl6Cegi1TLMZ9Cpznbgv99moC7REClI5gCkwA77LgbBGe+eGBiVX+WEZmKazJsE3Ed046bIYS/iUXWQhhxlw46p7pvGHmyfW7EmFQAbs3GqS8n47HrBBQqxOJe084hRJE/Z/JMyOYTbnGcrDMJ1MXcYxdt4g84ol1LYFNWy4Kl6hicWHjNZelgkB2TXnT7eUnWCpipm8JqUcz+Zc4iPJIp2KjWgph+ApUvLQz3pmGjXFvi6fMS5DH2LhSr42vokTqqmPmJNbLJm3u5sUosfdmp5b5y4LH05MO/mJXxIzc8XleweZluVkGBx7A9s9bX2lbUMGdRLeAGzmj/Mh+iH8+GBSTGh09dnNM3qOzMbNAzg8oV8TNoZq18BBE9kkgLiBCKNEUQofO8dJ+NyyVf/8ExKLSbObOieWr8kdkRg/BT3fepFIe1F8G4EOAR0JYeavXApq/Oqhwf8DoRos8Bw4svhjHa8qu8943KrVEH2k10BSTeb4+m12q73X9BEvDpyVeqwbux+XfUQJ3qlgBBKLBcbjJrj8iJN2rg0PLnGCs+07Hizgu5u21BfMhAFleRqYnIHHivx/TH4jnFWtOVpVKQRTM5OiAcQ94R2HLZF4kJfBauzTlNRDY9m38oJ8BsfuXK0tdHS8077eOyN7gghCsNVSMKKruA1Jiblue6fRcv/UA==
    admin-user: AgCXeXgP1EDYGekMFtbvSIkeWJe6MtFoodJ6kYYU8y/NOlMGmIWW88x/nh0U0Wn4W7FHQMSeqHTRmg4BswjqiSN3XVxraFa4w1Zng3Aj8t4NsRX+KBslWeKcNU3COHUWTqjR9N2cVRWYLbALPYx6fOVycYrlSBVQfU65ESyMmwlXFKpu/4EIX4M54G1t2hioSP5lMCbG5K6D7R9cKRgZ8ZPk3VaavKjTdjZ06IMXGGI6kiEu00FJQwcW/Ikxi3UZ/MUCjAkPvySWTJesylUemhKPVSaerQCTuiaJtAYPqvr8D319xPi0ACdLjJ1Cayn0DdXvBEb5i13LxbfQ6FD4eqijJtyv/wvZpn1QS+IsTtJYTGP2W1Gdcv2qBF27OKVz0nreW1RCojbZE+UJs1RaPjC7yWtVHtqSq6fOxQSxK9se8F8PzfXGXeubJnkXmo4FamHhhXXGHLExDwyq6AHVHAcdILMQc36pV7VREE0+BwO0thLFwTMj36+KLGM3hiXLU/I6Kq4BfFWgLoBd90N+9jFbWM61UsxuHAB2XGhHTYbhbdg9xtw4BBijtUOk5zvdYFegMpANI/phtg+KvUgVFMu+phKY22JHwmXaeCBHGBIZBsgOu6EtHDlAIx3mu1hjdMTvMdj2BSrEcm/vtTwhFBDI7L5s6jMBajNtSQcmF3qI2v7daHqa73U1yrfhwI/auBprzO3RjHhahRTH
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
    type: Opaque
