apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app-grafana
spec:
  type: kv-v2

  # mount path
  mount: homelab-secrets

  # path of the secret
  path: grafana-admin-credentials

  # dest k8s secret
  destination:
    name: grafana-admin-credentials
    create: true
    overwrite: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: observability-secrets