apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - sealedsecret.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack
    namespace: observability
    valuesFile: values.yaml
    version: 66.2.1
    includeCRDs: true