---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secret
  namespace: observability
spec:
  encryptedData:
    alertmanager.yaml: AgAwFhD6tiqPvwwN3SgZ1wRTfecjqL0nDk0ieDJzzP1Lw6kGz0CQxbtMrW+vLG+7hEmgmLlGmB533w+ovQfsaDDKopGfk5YyBN4bgT8m6LVDq9/k32WAx76Zm1YapDSRn/98RGrTgoJES2v4NsEGzanWWuY2q/UEJeERzoGBgZ3XHmb8fl0ZaGCz9YJf8YZYPlXYhnuHl7wNftxH7VLZiox8aicM+goFmLydYvHuRG5FTTFDDiUIA3XJoMYmcVLLX4KKtZwpV9tHL9Cr+w33SjH2ufZP8jDHrLAOjiJXTtki8YeAeo7cP3z0AZt4biBbvowLwsS8LFj1p59lC6W/K5iQFDB8TAcdGV10GxurBeruP81Q9OrJactGY+xB/YQBDZpOQw8IbDLPlIS9f5xaC3zTIKpDkaxqlbFkRhdPVq0lIJFoGIsCt+3S80U5OdKTnNS3nDHDXHGmFnYx6T/f3KTWwazt7kjsgTbqEgyVAE/Df2mTb+iRX+biMHI+rLo/jEeznR90bpiUpRHpkiHBciiCECoDmLu9gjNJ4JGzVi9lkZTGWdNn7GlwwBJsnoZRja8Sk5rmu9qn8rCqsBSx+Jz/cOBzNc1Np8WJGypKxB1eYVVt7gGfLVAZrkkMVBpTULi71rFKajan19dfuWnuIM4ZDIjmlLVGuKqe0AjGAy5x3Pt/2mxOVj4p+U73jLskp8XkvpfBLvtBybnbrhpQxJCLda7MRRPTUN21sh6W2ke1BASbkKSkCDCpZNv3TLKrQGzsPKwNyO4d13xTRtb3jSD726rNmpcpwrYWZscLIqQvtOV1mcvysEb0MH4rCyrCabdjx3XvPLe3UQAXVnRrIcGeFcTwOT75fVPWBfNtPaqx7kpX3ptih0nMuKU6YCdLFn6PuBJOcuE818OKu9+bdYau3en/q+CmhhpYMySm6CcaEcgrj1adoLfb2KB+adgLvHjss/lomE6tybkPZSsQPoYmVHaPIx4365W7Iedd5Ct7wFQ95Tg/OXwwfWI/L8I5ePsXTEIeHVuA26w0KeR/vYslABoiHsWCwpL6JhCGil04cJCdaQd1HZIQe42Z7jqZFaV4leGBGn/r982fJdAo6C2dbExZ
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secret
      namespace: observability
    type: Opaque
