---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secret
  namespace: observability
spec:
  encryptedData:
    alertmanager.yaml: AgAUcXzDwJzF0huhM7I+ozEU9Veq5Z2bS6Ibf0XTGluq9hRkbqg3hYldK+PCd+Du9/5Om8TZIbLYKMWTRsYDFAG3cOeJ6WhrufRLhC1boAN4jaW4a+vyH0YIwYJCLnhCuqNorDzjVwDNrqfscU52MKBcWN8nznG0WEvPM3fPDCALQp4fYYjCev3unXQFPEsP1FCZxJh+nbfvIhCxTQsaxemtY9z8PE4gEq2nzz/EOjDZBXoCmor+zdoI5LuUg3tnPi9CKX747Vp/yvv53KIR+RSptqIJSZMQfUTQAsKocONYerrrn9eCiAB+89T7r/FajbHiiyhXu01LGokdvnaRMej393GXNPhGyxUqcdo3rIwmbjzqJJIAJS+KJSn/GUPxA01tqiKnAadvVLyWV53Mldm512AJKvXb/EA7tl5zcweZsijJeLLds422hIyxvPtiOYhbD3+ZuQ8M+pTtFFFBlM4Xi7R0Gj6/o0J9UAh9DLwA6EMAvCt+aTWMgIEh1K2MaKRgTIdzoL+QEnRqMN9godvCwyPioyqY1KrJECS2SwskOqTlphFw5DaJ+R0cUYAJaG9ZG/w1QWuAIDsyhC4f/GlTkX1n4s036Ak1utEvARhcQkHzTL2BCAk7zMJ3NRWbn0XKWG1msrjeR3/DaQ65AjSBb4sqZP6fdeiGzGi/MK4syqnZuPlfRfMiWz+Vd3fER64msAJQ9m8tnx2zKRwIqNXuWkJ9olDhEb4BjeQU+mQeUkDewqKuadNb5ELjILnsUL6CD3VUCq8/wuuN7Hp5F66ORECqt70/ZMH+NbiDlIV3wIx0bsAFK/SDClAwEQTUSXa5ycYZlj5SuOUuDMKJU033xQQEKzdkJ8HDWYFxzQvS1Q0Ndp4nxpcF04QJe0JBkB8QA1dex3KkoDNRw7me59J9KNo6k1n1q6NmYLzfE7nLbegxYsuFyFY68KSpcyBFfrVyEk3SowQc9sZyRTf9Hh8kESO+UJLRyWvzjccczVV1YG6ZxcJ+dnExcSMwXstct2u7gDmZumMj5iDIPmSczlFmm38mMXCijhJkCHuVDAx/6FJnaES3WBMzQSIBLAhHCFWtQc7SW5Uq24kS9AHzUXg3QyB9m46lDnuB+NnIfSsXJZ0umHNpTiY3F+BAOy4eqPjyguivVvuXhnNP7Glv6WXqJMq8Py5cnFhPchCo4rF5Lb9dUANdrADKmsG7gKXomAXVAPPXn85MnppOkpuJtLuT7KwvM/u1Qq6sqwiayN90sAQn4ulTqkdGKejeLVkv+M6xv/QDkLyiErsp2vBInUVE1HBVM940kdavyF1yC+povA2wgwdSEBj3nK6NV+oeJcDmmK3841EJ5QEBTdBHLxdGS2XIIaQUujD3fYnjoHJE1HlNOff0T9OUmzsShGOrtQzUTZvZ4PnE+e/EB1ptwM5lu7RAd6Q817erkKtpjTxEGi/XLk2C9vZA4v9w1MG6shBEWHiORNhuJTt+FjqQ7P13eNLTqAxKpVLc4clkNRyQ+RMCNCTRaIKpg2DoeiHWydFpQ69RZHD6Qoxg2Er6bBGAsN6FjMM4er0Zx0YYhw==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secret
      namespace: observability
    type: Opaque
